"""empty message

Revision ID: 6c238aaf5eb4
Revises: 6ecbbf4be4b2
Create Date: 2022-02-17 02:47:23.948537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c238aaf5eb4'
down_revision = '6ecbbf4be4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_question')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_category_category'), 'category', ['category'], ['category_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_category_category'), type_='foreignkey')
        batch_op.drop_column('category')

    op.create_table('_alembic_tmp_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.category_name'], name='fk_question_category_category'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
